const products = [
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon 11", price:2500,image:"/images/pic (1).jpg"},
]

export default products